name: tylas_sweet
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  video_player: ^2.10.1
  url_launcher: ^6.3.1  # He añadido esto para que funcionen los botones de WhatsApp y TikTok

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Registro de Carpetas
  assets:
    - assets/images/
    - assets/videos/
    - assets/fonts/

  # Registro de Fuentes
  fonts:
    - family: CreamCake
      fonts:
        - asset: assets/fonts/CreamCake.ttf