name: tylas_sweet
description: "Catalogo Tylas Sweet Premium"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # LIBRERÍAS DE MAGIA DE DISEÑO (Añadidas aquí)
  google_fonts: ^6.1.0          # Fuentes elegantes
  url_launcher: ^6.2.1          # Para WhatsApp
  flutter_animate: ^4.2.0+1     # Animaciones increíbles
  flutter_staggered_animations: ^1.1.1 # Animación de la galería

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    # Asegúrate de tener tu logo.png aquí dentro de assets/images/